spring:
   application:
      name: gateway-service
   cloud:
      gateway:
         routes:
          - id: car-service
            uri: lb://car-service
            predicates:
               - Path=/v1/car/**
          - id: variant-service
            uri: lb://variant-service
            predicates:
               - Path=/v1/variant/**
         discovery:
            locator:
               enabled: true 
      compatibility-verifier:
         enabled: false

logging:
   pattern:
      level: "%5p [${spring.application.name:},%X${traceId:-},%X${spanId:-}]"
   level:
     org.springframework.web: DEBUG
server:
   port: 8889
  
eureka:
   client:
      register-with-eureka: true
      service-url:
         defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
       
   instance:
      prefer-ip-address: true
      
      
      
management:
   endpoints:
      web:
         exposure:
            include: "*"
        
        
        
